# Generated by Django 5.0.2 on 2024-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='parser/'),
        ),
    ]
