# Generated by Django 5.0.2 on 2024-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название телефона')),
                ('description', models.TextField(verbose_name='Укажите описание телефона')),
                ('image_1', models.ImageField(upload_to='', verbose_name='Загрузите фото')),
                ('image2', models.URLField(verbose_name='Укажите ссылку на фото')),
                ('price', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('discount', models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('50%', '50%'), ('75%', '75%')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
