# Generated by Django 5.0.2 on 2024-02-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_shop', '0002_phoneshop_gift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneshop',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.CreateModel(
            name='ReviewsPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Напишите комент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_phones', to='phone_shop.phoneshop')),
            ],
        ),
    ]
